<a href="https://colab.research.google.com/github/payaljain2003/NLP/blob/main/Output_HS_values_LSTM_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


code to check output and hidden state values are same in a LSTM


In [1]:
import numpy as np
from keras.layers import LSTM, Input
from keras.models import Model

# Define the LSTM cell with return_sequences=True and return_state=True
# This way, it will return both the output (y) and the hidden state (h)
lstm_units = 5
input_dim = 3  # Dimensionality of the input
inputs = Input(shape=(None, input_dim))  # None indicates variable sequence length
lstm_layer = LSTM(lstm_units, return_sequences=True, return_state=True)
y, h, c = lstm_layer(inputs)

# Create the model
model = Model(inputs=inputs, outputs=[y, h])

# Initialize input data for a single time step
input_data = np.random.rand(1, 1, input_dim)  # Batch size of 1, sequence length of 1

# Run the LSTM cell for one time step
output_data, hidden_state_data = model.predict(input_data)

print("Output (y) shape:", output_data.shape)  # Output (y) shape should be (1, 1, lstm_units)
print("Hidden state (h) shape:", hidden_state_data.shape)  # Hidden state (h) shape should be (1, lstm_units)

# Print the output (y) and the hidden state (h) to compare their values
print("Output (y):", output_data)
print("Hidden state (h):", hidden_state_data)


1/1 [==============================] - 1s 1s/step
Output (y) shape: (1, 1, 5)
Hidden state (h) shape: (1, 5)
Output (y): [[[ 0.0261872   0.12302117  0.02824509 -0.00624926  0.00799813]]]
Hidden state (h): [[ 0.0261872   0.12302117  0.02824509 -0.00624926  0.00799813]]


In [2]:
from __future__ import print_function, division
from builtins import range, input

In [3]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

In [4]:
try:
  import keras.backend as K
  if len(K.tensorflow_backend._get_available_gpus()) > 0:
    from keras.layers import CuDNNLSTM as LSTM
    from keras.layers import CuDNNGRU as GRU
except:
  pass

In [5]:
T = 8
D = 2
M = 3


In [6]:
X = np.random.randn(1, T, D)

In [8]:
def lstm1():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)

def lstm2():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences = True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o)
  print("h:", h)
  print("c:", c)

def gru1():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)

def gru2():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences = True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)


print("lstm1:")
lstm1()
print("lstm2:")
lstm2()
print("gru1:")
gru1()
print("gru2:")
gru2()


lstm1:


1/1 [==============================] - 1s 715ms/step
o: [[ 0.17795984  0.21558331 -0.27621305]]
h: [[ 0.17795984  0.21558331 -0.27621305]]
c: [[ 0.27628297  0.43326348 -0.5704122 ]]
lstm2:


1/1 [==============================] - 0s 451ms/step
o: [[[ 0.08229339 -0.02741942  0.05275549]
  [ 0.10619942 -0.06647743  0.08746725]
  [ 0.07386883 -0.01293178 -0.00468102]
  [-0.15305232  0.16848214 -0.1049858 ]
  [-0.1150966   0.11102268 -0.11575219]
  [ 0.00526281  0.12870704 -0.13853502]
  [-0.08156968  0.16344193 -0.1419556 ]
  [-0.07196441  0.10830326 -0.10746338]]]
h: [[-0.07196441  0.10830326 -0.10746338]]
c: [[-0.13029683  0.40801644 -0.543639  ]]
gru1:
1/1 [==============================] - 0s 421ms/step
o: [[ 0.2424083  -0.30335814  0.35967353]]
h: [[ 0.2424083  -0.30335814  0.35967353]]
gru2:
1/1 [==============================] - 0s 385ms/step
o: [[[-0.08307579 -0.03189086 -0.12740374]
  [-0.03166153  0.10437801 -0.13943118]
  [-0.24341986 -0.30241272 -0.23506108]
  [ 0.29289958 -0.38964283  0.57288873]
  [-0.2065455  -0.5593924   0.29013035]
  [-0.17194659  0.04164326  0.03069071]
  [ 0.00334617 -0.08063549  0.1799569 ]
  [-0.22318101 -0.35634467  0.04321803]]]
h: [[-0